# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"Q\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\"e\n\rStockResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x15\n\rcurrent_stock\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x04 \x01(\x03\"g\n\x0fReserveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fremaining_stock\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x04 \x01(\x03\"\\\n\x12UpdateStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x17\n\x0fquantity_change\x18\x02 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\"i\n\x13UpdateStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rupdated_stock\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x04 \x01(\x03\x32\xea\x01\n\x10InventoryService\x12\x41\n\nCheckStock\x12\x19.inventory.ProductRequest\x1a\x18.inventory.StockResponse\x12\x45\n\x0cReserveStock\x12\x19.inventory.ProductRequest\x1a\x1a.inventory.ReserveResponse\x12L\n\x0bUpdateStock\x12\x1d.inventory.UpdateStockRequest\x1a\x1e.inventory.UpdateStockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=30
  _globals['_PRODUCTREQUEST']._serialized_end=111
  _globals['_STOCKRESPONSE']._serialized_start=113
  _globals['_STOCKRESPONSE']._serialized_end=214
  _globals['_RESERVERESPONSE']._serialized_start=216
  _globals['_RESERVERESPONSE']._serialized_end=319
  _globals['_UPDATESTOCKREQUEST']._serialized_start=321
  _globals['_UPDATESTOCKREQUEST']._serialized_end=413
  _globals['_UPDATESTOCKRESPONSE']._serialized_start=415
  _globals['_UPDATESTOCKRESPONSE']._serialized_end=520
  _globals['_INVENTORYSERVICE']._serialized_start=523
  _globals['_INVENTORYSERVICE']._serialized_end=757
# @@protoc_insertion_point(module_scope)
